const LYBRATE_SPECIALTIES = [
  "General Physician",
  "Dermatologist",
  "Cardiologist",
  "Neurologist",
  "Neurosurgeon",
  "Orthopedic Surgeon",
  "Pediatrician",
  "Gynecologist",
  "Obstetrician",
  "ENT Specialist",
  "Ophthalmologist",
  "Dentist",
  "Psychiatrist",
  "Psychologist",
  "Pulmonologist",
  "Gastroenterologist",
  "General Surgeon",
  "Urologist",
  "Nephrologist",
  "Endocrinologist",
  "Oncologist",
  "Hematologist",
  "Rheumatologist",
  "Radiologist",
  "Plastic Surgeon",
  "Cosmetic Surgeon",
  "Physiotherapist",
  "Dietitian",
  "Nutritionist",
  "Sexologist",
  "Ayurveda",
  "Homeopath",
  "Unani",
  "Yoga & Naturopathy",
  "Speech Therapist",
  "Audiologist",
  "Podiatrist",
  "Pain Management Specialist",
  "Internal Medicine Specialist",
  "Family Physician",
  "Diabetologist",
  "Infectious Disease Specialist",
  "Laparoscopic Surgeon",
  "Vascular Surgeon",
  "Proctologist",
  "Fertility Specialist",
  "IVF Specialist",
  "Andrologist",
  "Pediatric Surgeon"
];

module.exports = {
  LYBRATE_SPECIALTIES
};
