const mongoose = require('mongoose');

const articleSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true,
  },
  category: {
    type: String,
    required: true,
    trim: true,
  },
  content: {
    type: String,
    required: true,
  },
  embedding: {
    type: [Number], // 768-dimensional array of floats generated by text-embedding-004
    required: true,
  },
}, {
  timestamps: true,
});

module.exports = mongoose.model('Article', articleSchema);
